# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hmn < Formula
  desc "HeavyMetal Network provider node CLI"
  homepage "https://heavymetal.network"
  version "0.16.78"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heavymetal-network/hmn-cli-pub/releases/download/v0.16.78/hmn_0.16.78_darwin_amd64.tar.gz"
      sha256 "15335d475064192f02701b919e1687335f0721d7fa02aac277376b3e41d05871"

      define_method(:install) do
        bin.install "hmn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heavymetal-network/hmn-cli-pub/releases/download/v0.16.78/hmn_0.16.78_darwin_arm64.tar.gz"
      sha256 "120870b0d4406f34f75f2f4ea63c9dde33e5e6a8f2e67ea6340753e0b1f4e33c"

      define_method(:install) do
        bin.install "hmn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heavymetal-network/hmn-cli-pub/releases/download/v0.16.78/hmn_0.16.78_linux_amd64.tar.gz"
      sha256 "d6c342d97bdb21382c3d5793bf721cd395eebd70cf404ed54d4dc4894b5be6b4"
      define_method(:install) do
        bin.install "hmn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heavymetal-network/hmn-cli-pub/releases/download/v0.16.78/hmn_0.16.78_linux_arm64.tar.gz"
      sha256 "6f8d9de6ab6d2eb8cfd4fc319e2ef5719b70b4c722edf1aefcc7a352e9d7e12b"
      define_method(:install) do
        bin.install "hmn"
      end
    end
  end

  test do
    system "#{bin}/hmn", "--version"
  end
end
