# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hmn < Formula
  desc "HeavyMetal Network provider node CLI"
  homepage "https://heavymetal.network"
  version "0.17.56"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/heavymetal-network/hmn-cli-pub/releases/download/v0.17.56/hmn_0.17.56_darwin_amd64.tar.gz"
      sha256 "3e9b2c5977274a71bd78a17f180932fe50608a95ef7591def4e6be2561d9bdff"

      define_method(:install) do
        bin.install "hmn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/heavymetal-network/hmn-cli-pub/releases/download/v0.17.56/hmn_0.17.56_darwin_arm64.tar.gz"
      sha256 "07ab0fb855e0ddda492c217a113eb440e9ed6f716bf58a130b23194f7e6e40d6"

      define_method(:install) do
        bin.install "hmn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/heavymetal-network/hmn-cli-pub/releases/download/v0.17.56/hmn_0.17.56_linux_amd64.tar.gz"
      sha256 "17f6e8400bcaa379426d22b9573073fb0d1cc54c6547319148a46af40fa8d59f"
      define_method(:install) do
        bin.install "hmn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/heavymetal-network/hmn-cli-pub/releases/download/v0.17.56/hmn_0.17.56_linux_arm64.tar.gz"
      sha256 "64747e46d2629af3d0f7cfacbbf5ce4550034657a7752e6d117e97d2a6c0a172"
      define_method(:install) do
        bin.install "hmn"
      end
    end
  end

  test do
    system "#{bin}/hmn", "--version"
  end
end
